# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person-reid.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='person-reid.proto',
  package='godeye_service.person_reid',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11person-reid.proto\x12\x1agodeye_service.person_reid\"@\n\x0e\x46\x65\x61tureRequest\x12.\n\x03img\x18\x01 \x01(\x0b\x32!.godeye_service.person_reid.Image\"!\n\x0f\x46\x65\x61tureResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"\x18\n\x05Image\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x32\xe3\x01\n\nPersonReID\x12g\n\nGetFeature\x12*.godeye_service.person_reid.FeatureRequest\x1a+.godeye_service.person_reid.FeatureResponse\"\x00\x12l\n\x0bGetFeatures\x12*.godeye_service.person_reid.FeatureRequest\x1a+.godeye_service.person_reid.FeatureResponse\"\x00(\x01\x30\x01\x62\x06proto3'
)




_FEATUREREQUEST = _descriptor.Descriptor(
  name='FeatureRequest',
  full_name='godeye_service.person_reid.FeatureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='godeye_service.person_reid.FeatureRequest.img', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=113,
)


_FEATURERESPONSE = _descriptor.Descriptor(
  name='FeatureResponse',
  full_name='godeye_service.person_reid.FeatureResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector', full_name='godeye_service.person_reid.FeatureResponse.vector', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=148,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='godeye_service.person_reid.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='godeye_service.person_reid.Image.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=174,
)

_FEATUREREQUEST.fields_by_name['img'].message_type = _IMAGE
DESCRIPTOR.message_types_by_name['FeatureRequest'] = _FEATUREREQUEST
DESCRIPTOR.message_types_by_name['FeatureResponse'] = _FEATURERESPONSE
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FeatureRequest = _reflection.GeneratedProtocolMessageType('FeatureRequest', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREREQUEST,
  '__module__' : 'person_reid_pb2'
  # @@protoc_insertion_point(class_scope:godeye_service.person_reid.FeatureRequest)
  })
_sym_db.RegisterMessage(FeatureRequest)

FeatureResponse = _reflection.GeneratedProtocolMessageType('FeatureResponse', (_message.Message,), {
  'DESCRIPTOR' : _FEATURERESPONSE,
  '__module__' : 'person_reid_pb2'
  # @@protoc_insertion_point(class_scope:godeye_service.person_reid.FeatureResponse)
  })
_sym_db.RegisterMessage(FeatureResponse)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'person_reid_pb2'
  # @@protoc_insertion_point(class_scope:godeye_service.person_reid.Image)
  })
_sym_db.RegisterMessage(Image)



_PERSONREID = _descriptor.ServiceDescriptor(
  name='PersonReID',
  full_name='godeye_service.person_reid.PersonReID',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=177,
  serialized_end=404,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFeature',
    full_name='godeye_service.person_reid.PersonReID.GetFeature',
    index=0,
    containing_service=None,
    input_type=_FEATUREREQUEST,
    output_type=_FEATURERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFeatures',
    full_name='godeye_service.person_reid.PersonReID.GetFeatures',
    index=1,
    containing_service=None,
    input_type=_FEATUREREQUEST,
    output_type=_FEATURERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PERSONREID)

DESCRIPTOR.services_by_name['PersonReID'] = _PERSONREID

# @@protoc_insertion_point(module_scope)
